name: Tag
version: '1.0-SNAPSHOT'
main: luna.tag.Main
api-version: '1.21'
commands:
  taggingitem:
    usage: use it
    description: use it
  spoon:
    usage: spoon
    description: spoon
  game:
    usage: /<command> <start/end> [<hotpotato>]
    description: Start the game, or end it.
  spawn:
    usage: /<command> [<set>] [<map name>]
    description: Go to spawn, or set a spawn.
  map:
    usage: /<command> [<set/add/remove/randomize>] [<name>]
    description: Set, remove, add, or randomize the current map.
  firework:
    usage: /<command> <set> <color1> [<color2>] [<color3>]
    description: Set firework color
