name: Tag
version: '1.0-SNAPSHOT'
main: luna.tag.Main
api-version: '1.21'
commands:
  taggingitem:
    usage: use it
    description: use it
  spoon:
    usage: spoon
    description: spoon
  game:
    usage: /<command> <start/end> [<hotpotato>]
    description: Start the game, or end it.
